<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Financial Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; margin-bottom: 10px; }
        .stats { margin-bottom: 20px; }
        .stats table { width: 100%; border-collapse: collapse; }
        .stats td { padding: 5px; border: 1px solid #ddd; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 8px; text-align: left; border: 1px solid #ddd; }
        th { background-color: #f0f0f0; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Financial Report</h1>
        <p>Period: {{ \Carbon\Carbon::parse($dateFrom)->format('Y-m-d') }} to {{ \Carbon\Carbon::parse($dateTo)->format('Y-m-d') }}</p>
        <p>Generated: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="stats">
        <table>
            <tr>
                <td><strong>Total Revenue:</strong></td>
                <td>${{ number_format($stats['total_revenue'] ?? 0, 2) }}</td>
                <td><strong>Total Invoices:</strong></td>
                <td>{{ $stats['total_invoices'] ?? 0 }}</td>
            </tr>
            <tr>
                <td><strong>Paid Invoices:</strong></td>
                <td>{{ $stats['paid_invoices'] ?? 0 }}</td>
                <td><strong>Pending Invoices:</strong></td>
                <td>{{ $stats['pending_invoices'] ?? 0 }}</td>
            </tr>
            <tr>
                <td><strong>Overdue Invoices:</strong></td>
                <td>{{ $stats['overdue_invoices'] ?? 0 }}</td>
                <td><strong>Average Payment:</strong></td>
                <td>${{ number_format($stats['average_payment'] ?? 0, 2) }}</td>
            </tr>
        </table>
    </div>

    @if($revenueByProvider && count($revenueByProvider) > 0)
    <h2 style="margin-top: 20px; margin-bottom: 10px;">Revenue by Service Provider</h2>
    <table>
        <thead>
            <tr>
                <th>Provider</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($revenueByProvider as $provider => $revenue)
            <tr>
                <td>{{ $provider }}</td>
                <td>${{ number_format($revenue, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if($monthlyRevenue && count($monthlyRevenue) > 0)
    <h2 style="margin-top: 20px; margin-bottom: 10px;">Monthly Revenue</h2>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthlyRevenue as $data)
            <tr>
                <td>{{ $data['month'] }}</td>
                <td>${{ number_format($data['total'], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>Page 1 - Generated by eBill Payment Platform</p>
    </div>
</body>
</html>

