<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payments Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; margin-bottom: 10px; }
        .stats { margin-bottom: 20px; }
        .stats table { width: 100%; border-collapse: collapse; }
        .stats td { padding: 5px; border: 1px solid #ddd; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 8px; text-align: left; border: 1px solid #ddd; }
        th { background-color: #f0f0f0; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payments Report</h1>
        @if($dateFrom && $dateTo)
            <p>Period: {{ \Carbon\Carbon::parse($dateFrom)->format('Y-m-d') }} to {{ \Carbon\Carbon::parse($dateTo)->format('Y-m-d') }}</p>
        @endif
        <p>Generated: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    @if(isset($stats))
    <div class="stats">
        <table>
            <tr>
                <td><strong>Total Payments:</strong></td>
                <td>{{ $stats['total_payments'] ?? 0 }}</td>
                <td><strong>Total Amount:</strong></td>
                <td>${{ number_format($stats['total_amount'] ?? 0, 2) }}</td>
            </tr>
            <tr>
                <td><strong>Pending Amount:</strong></td>
                <td>${{ number_format($stats['pending_amount'] ?? 0, 2) }}</td>
                <td><strong>Failed Amount:</strong></td>
                <td>${{ number_format($stats['failed_amount'] ?? 0, 2) }}</td>
            </tr>
        </table>
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>Reference</th>
                <th>Invoice</th>
                <th>User</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Type</th>
                <th>Method</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payments as $payment)
            <tr>
                <td>{{ $payment->payment_reference ?? 'N/A' }}</td>
                <td>{{ $payment->invoice->invoice_number ?? 'N/A' }}</td>
                <td>{{ $payment->user->name ?? 'N/A' }}</td>
                <td>${{ number_format($payment->amount, 2) }}</td>
                <td>{{ ucfirst($payment->status) }}</td>
                <td>{{ ucfirst($payment->payment_type) }}</td>
                <td>{{ $payment->paymentMethod->type ?? 'N/A' }}</td>
                <td>{{ $payment->created_at->format('Y-m-d H:i') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Page 1 - Generated by eBill Payment Platform</p>
    </div>
</body>
</html>

