<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Usage Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; margin-bottom: 10px; }
        .stats { margin-bottom: 20px; }
        .stats table { width: 100%; border-collapse: collapse; }
        .stats td { padding: 5px; border: 1px solid #ddd; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 8px; text-align: left; border: 1px solid #ddd; }
        th { background-color: #f0f0f0; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Usage Report</h1>
        <p>Period: {{ \Carbon\Carbon::parse($dateFrom)->format('Y-m-d') }} to {{ \Carbon\Carbon::parse($dateTo)->format('Y-m-d') }}</p>
        <p>Generated: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="stats">
        <table>
            <tr>
                <td><strong>Total Providers:</strong></td>
                <td>{{ $stats['total_providers'] ?? 0 }}</td>
                <td><strong>Active Providers:</strong></td>
                <td>{{ $stats['active_providers'] ?? 0 }}</td>
            </tr>
            <tr>
                <td><strong>Total Invoices:</strong></td>
                <td>{{ $stats['total_invoices'] ?? 0 }}</td>
                <td><strong>Active Users:</strong></td>
                <td>{{ $stats['total_users_active'] ?? 0 }}</td>
            </tr>
        </table>
    </div>

    @if($providerUsage && count($providerUsage) > 0)
    <h2 style="margin-top: 20px; margin-bottom: 10px;">Service Provider Usage</h2>
    <table>
        <thead>
            <tr>
                <th>Provider</th>
                <th>Status</th>
                <th>Total Invoices</th>
                <th>Paid Invoices</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($providerUsage as $provider)
            <tr>
                <td>{{ $provider->company_name }}</td>
                <td>{{ $provider->is_active ? 'Active' : 'Inactive' }}</td>
                <td>{{ $provider->invoices_count ?? 0 }}</td>
                <td>{{ $provider->paid_invoices_count ?? 0 }}</td>
                <td>${{ number_format($provider->total_revenue ?? 0, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if($userActivity && count($userActivity) > 0)
    <h2 style="margin-top: 20px; margin-bottom: 10px;">User Activity</h2>
    <table>
        <thead>
            <tr>
                <th>User</th>
                <th>Email</th>
                <th>Invoices</th>
                <th>Payments</th>
            </tr>
        </thead>
        <tbody>
            @foreach($userActivity as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->invoices_count ?? 0 }}</td>
                <td>{{ $user->payments_count ?? 0 }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>Page 1 - Generated by eBill Payment Platform</p>
    </div>
</body>
</html>

