<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; margin-bottom: 10px; }
        .stats { margin-bottom: 20px; }
        .stats table { width: 100%; border-collapse: collapse; }
        .stats td { padding: 5px; border: 1px solid #ddd; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 8px; text-align: left; border: 1px solid #ddd; }
        th { background-color: #f0f0f0; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Users Report</h1>
        @if($dateFrom && $dateTo)
            <p>Period: {{ \Carbon\Carbon::parse($dateFrom)->format('Y-m-d') }} to {{ \Carbon\Carbon::parse($dateTo)->format('Y-m-d') }}</p>
        @endif
        <p>Generated: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    @if(isset($stats))
    <div class="stats">
        <table>
            <tr>
                <td><strong>Total Users:</strong></td>
                <td>{{ $stats['total_users'] ?? 0 }}</td>
                <td><strong>Active Users:</strong></td>
                <td>{{ $stats['active_users'] ?? 0 }}</td>
            </tr>
            <tr>
                <td><strong>Inactive Users:</strong></td>
                <td>{{ $stats['inactive_users'] ?? 0 }}</td>
            </tr>
        </table>
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Role</th>
                <th>Status</th>
                <th>Invoices</th>
                <th>Payments</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->phone ?? 'N/A' }}</td>
                <td>{{ $user->roles->pluck('name')->join(', ') ?: 'N/A' }}</td>
                <td>{{ $user->is_active ? 'Active' : 'Inactive' }}</td>
                <td>{{ $user->invoices_count ?? 0 }}</td>
                <td>{{ $user->payments_count ?? 0 }}</td>
                <td>{{ $user->created_at->format('Y-m-d') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Page 1 - Generated by eBill Payment Platform</p>
    </div>
</body>
</html>

