import { Invoice, Payment, Ticket, User, PaymentMethodDetails, DashboardStats, TicketReply } from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1 234 567 890',
    role: 'customer',
    status: 'active',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@acmecorp.com',
    phone: '+1 234 567 891',
    role: 'provider',
    status: 'active',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Admin User',
    email: 'admin@ebill.com',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2023-12-01'),
  },
  {
    id: '4',
    name: 'Sarah Wilson',
    email: 'sarah@support.com',
    role: 'support',
    status: 'active',
    createdAt: new Date('2024-03-01'),
  },
];

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    title: 'Web Development Services',
    description: 'Monthly retainer for web development and maintenance',
    customerId: '1',
    customerName: 'John Doe',
    providerId: '2',
    providerName: 'Acme Corp',
    amount: 2500,
    taxAmount: 250,
    totalAmount: 2750,
    status: 'pending',
    issueDate: new Date('2024-12-01'),
    dueDate: new Date('2024-12-31'),
    createdAt: new Date('2024-12-01'),
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    title: 'Cloud Hosting Services',
    description: 'Annual cloud hosting subscription',
    customerId: '1',
    customerName: 'John Doe',
    providerId: '2',
    providerName: 'Acme Corp',
    amount: 1200,
    taxAmount: 120,
    totalAmount: 1320,
    status: 'paid',
    issueDate: new Date('2024-11-15'),
    dueDate: new Date('2024-12-15'),
    paidAt: new Date('2024-11-20'),
    createdAt: new Date('2024-11-15'),
  },
  {
    id: '3',
    invoiceNumber: 'INV-2024-003',
    title: 'Consulting Services',
    description: 'Business consulting - Q4 2024',
    customerId: '1',
    customerName: 'John Doe',
    providerId: '2',
    providerName: 'Acme Corp',
    amount: 5000,
    taxAmount: 500,
    totalAmount: 5500,
    status: 'overdue',
    issueDate: new Date('2024-10-01'),
    dueDate: new Date('2024-11-01'),
    createdAt: new Date('2024-10-01'),
  },
  {
    id: '4',
    invoiceNumber: 'INV-2024-004',
    title: 'Software License',
    description: 'Enterprise software license renewal',
    customerId: '1',
    customerName: 'John Doe',
    providerId: '2',
    providerName: 'TechSolutions Inc',
    amount: 3500,
    taxAmount: 350,
    totalAmount: 3850,
    status: 'pending',
    issueDate: new Date('2024-12-10'),
    dueDate: new Date('2025-01-10'),
    createdAt: new Date('2024-12-10'),
  },
  {
    id: '5',
    invoiceNumber: 'INV-2024-005',
    title: 'Security Audit',
    description: 'Annual security assessment and penetration testing',
    customerId: '1',
    customerName: 'John Doe',
    providerId: '2',
    providerName: 'SecureNet',
    amount: 8000,
    taxAmount: 800,
    totalAmount: 8800,
    status: 'paid',
    issueDate: new Date('2024-11-01'),
    dueDate: new Date('2024-11-30'),
    paidAt: new Date('2024-11-25'),
    createdAt: new Date('2024-11-01'),
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: '1',
    reference: 'PAY-2024-001',
    invoiceId: '2',
    invoiceNumber: 'INV-2024-002',
    customerId: '1',
    customerName: 'John Doe',
    amount: 1320,
    status: 'completed',
    method: 'card',
    transactionId: 'TXN_abc123xyz',
    createdAt: new Date('2024-11-20'),
  },
  {
    id: '2',
    reference: 'PAY-2024-002',
    invoiceId: '5',
    invoiceNumber: 'INV-2024-005',
    customerId: '1',
    customerName: 'John Doe',
    amount: 8800,
    status: 'completed',
    method: 'bank_transfer',
    transactionId: 'TXN_def456uvw',
    createdAt: new Date('2024-11-25'),
  },
];

// Mock Payment Methods
export const mockPaymentMethods: PaymentMethodDetails[] = [
  {
    id: '1',
    type: 'card',
    lastFour: '4242',
    brand: 'Visa',
    holderName: 'John Doe',
    isDefault: true,
    expiryMonth: 12,
    expiryYear: 2026,
  },
  {
    id: '2',
    type: 'card',
    lastFour: '5555',
    brand: 'Mastercard',
    holderName: 'John Doe',
    isDefault: false,
    expiryMonth: 6,
    expiryYear: 2025,
  },
  {
    id: '3',
    type: 'bank_account',
    lastFour: '7890',
    bankName: 'Chase Bank',
    holderName: 'John Doe',
    isDefault: false,
  },
];

// Mock Tickets
export const mockTickets: Ticket[] = [
  {
    id: '1',
    ticketNumber: 'TKT-001',
    subject: 'Payment not reflecting in account',
    description: 'I made a payment yesterday but it is still showing as pending.',
    category: 'Billing',
    status: 'open',
    priority: 'high',
    customerId: '1',
    customerName: 'John Doe',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: '2',
    ticketNumber: 'TKT-002',
    subject: 'Request for invoice correction',
    description: 'The invoice INV-2024-001 has incorrect billing address.',
    category: 'Invoice',
    status: 'in_progress',
    priority: 'medium',
    customerId: '1',
    customerName: 'John Doe',
    assignedTo: '4',
    assignedToName: 'Sarah Wilson',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: '3',
    ticketNumber: 'TKT-003',
    subject: 'Unable to download PDF invoice',
    description: 'Getting an error when trying to download invoice PDF.',
    category: 'Technical',
    status: 'resolved',
    priority: 'low',
    customerId: '1',
    customerName: 'John Doe',
    assignedTo: '4',
    assignedToName: 'Sarah Wilson',
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-08'),
    closedAt: new Date('2024-12-08'),
  },
];

// Mock Ticket Replies
export const mockTicketReplies: TicketReply[] = [
  {
    id: '1',
    ticketId: '2',
    userId: '1',
    userName: 'John Doe',
    message: 'Please correct the billing address from "123 Old Street" to "456 New Avenue".',
    isStaff: false,
    createdAt: new Date('2024-12-10T10:30:00'),
  },
  {
    id: '2',
    ticketId: '2',
    userId: '4',
    userName: 'Sarah Wilson',
    message: 'Thank you for reaching out. I have forwarded this to our billing team and we will update the invoice shortly.',
    isStaff: true,
    createdAt: new Date('2024-12-11T09:15:00'),
  },
  {
    id: '3',
    ticketId: '2',
    userId: '4',
    userName: 'Sarah Wilson',
    message: 'The invoice has been updated with the correct address. A new PDF has been generated and sent to your email.',
    isStaff: true,
    createdAt: new Date('2024-12-12T14:00:00'),
  },
];

// Dashboard Stats
export const mockCustomerStats: DashboardStats = {
  totalInvoices: 5,
  pendingInvoices: 2,
  overdueInvoices: 1,
  paidInvoices: 2,
  totalPaidAmount: 10120,
  pendingAmount: 12100,
  totalRevenue: 0,
  totalUsers: 0,
  openTickets: 1,
  resolvedTickets: 1,
};

export const mockAdminStats: DashboardStats = {
  totalInvoices: 156,
  pendingInvoices: 45,
  overdueInvoices: 12,
  paidInvoices: 99,
  totalPaidAmount: 245680,
  pendingAmount: 78540,
  totalRevenue: 324220,
  totalUsers: 48,
  openTickets: 8,
  resolvedTickets: 127,
};

// Chart data
export const monthlyRevenueData = [
  { month: 'Jan', revenue: 45000, invoices: 28 },
  { month: 'Feb', revenue: 52000, invoices: 32 },
  { month: 'Mar', revenue: 48000, invoices: 29 },
  { month: 'Apr', revenue: 61000, invoices: 38 },
  { month: 'May', revenue: 55000, invoices: 34 },
  { month: 'Jun', revenue: 67000, invoices: 42 },
  { month: 'Jul', revenue: 72000, invoices: 45 },
  { month: 'Aug', revenue: 69000, invoices: 43 },
  { month: 'Sep', revenue: 78000, invoices: 48 },
  { month: 'Oct', revenue: 82000, invoices: 51 },
  { month: 'Nov', revenue: 91000, invoices: 56 },
  { month: 'Dec', revenue: 95000, invoices: 58 },
];

export const invoiceStatusData = [
  { name: 'Paid', value: 99, color: 'hsl(158 64% 52%)' },
  { name: 'Pending', value: 45, color: 'hsl(38 92% 50%)' },
  { name: 'Overdue', value: 12, color: 'hsl(0 84% 60%)' },
];

export const paymentMethodData = [
  { name: 'Credit Card', value: 65 },
  { name: 'Bank Transfer', value: 25 },
  { name: 'Digital Wallet', value: 10 },
];
